version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=Rates
    ports:
      - 5432:5432
 
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin1    
    environment:
      - PGADMIN_DEFAULT_EMAIL=atilla@admin.com
      - PGADMIN_DEFAULT_PASSWORD=123
    ports:
      - 80:80
    links:
      - postgres
